from pydantic import BaseModel, Field
from typing import List, Literal, Optional


class SearchQuery(BaseModel):
    id: int = Field(
        description="Unique identifier for the list of question"
    )
    query: str = Field(
        description="List of search queries to be used for web search."
    )
    rationale: str = Field(
        description="A bref description why this queries are relevant to the resaerch topic and user question."
    )
    
class TaskList(BaseModel):
    id: int = Field(
        description="Unique identifier for the list of task"
    )
    task: str =Field(
        description="List of task list agent need to perform inorder to complete user question."
    )
    status: Literal["Completed", "In Progress", "Not Started"] = Field(
        description="A literal to track the progress of sub agent"
    )
    rationale: str = Field(
        description="A breif description why this tasks are relevant to complete user query."
    )
    
class TaskListSchema(BaseModel):
    tasks: List[TaskList] = Field(
        description="List of dictnary of TaskList "
    )
    

class Classifier(BaseModel):
    sections: List[str] = Field(
        description="List of section that are matched from given text"
    )
    reason: str = Field(
        description="A breif descirption why this seciton are relevant to particular section"
    )
    
class FollowQuestion(BaseModel):
    question: List[SearchQuery] = Field(
        description="List of follow up question generated by LLM"
    )
    
    
class ReferenceItem(BaseModel):
    id: str = Field(description="Citation key like [1], [2] or a bibtex key")
    ieee: str = Field(description="IEEE-formatted reference string")

class Topic(BaseModel):
    brief: str = Field(description="A breif descirption why this seciton are relevant to particular section")
    topic: str = Field(description="Name of the topic included iin the report")
class Topics(BaseModel):
    report: List[Topic] = Field(
        description="List of topic required for report"
    )

class QualityCheck(BaseModel):
    passed: bool = Field(
        description="Whether the section passes quality standards. True if score >= 0.7, the section is well-written, comprehensive, properly cited, and meets the 500-2000 word requirement"
    )
    score: float = Field(
        description="Overall quality score from 0.0 to 1.0 where 0.7+ means passing quality"
    )
    feedback: List[str] = Field(
        description="List of specific quality issues, missing content areas, or suggestions for improvement. Be precise about what needs fixing."
    )
    