from pydantic import BaseModel, Field
from typing import List, Literal


class SearchQuery(BaseModel):
    id: int = Field(
        description="Unique identifier for the list of question"
    )
    query: str = Field(
        description="List of search queries to be used for web search."
    )
    rationale: str = Field(
        description="A bref description why this queries are relevant to the resaerch topic and user question."
    )
    
class TaskList(BaseModel):
    id: int = Field(
        description="Unique identifier for the list of task"
    )
    task: str =Field(
        description="List of task list agent need to perform inorder to complete user question."
    )
    status: Literal["Completed", "In Progress", "Not Started"] = Field(
        description="A literal to track the progress of sub agent"
    )
    rationale: str = Field(
        description="A breif description why this tasks are relevant to complete user query."
    )
    
class TaskListSchema(BaseModel):
    tasks: List[TaskList] = Field(
        description="List of dictnary of TaskList "
    )
    

class Classifier(BaseModel):
    sections: List[str] = Field(
        description="List of section that are matched from given text"
    )
    reason: str = Field(
        description="A breif descirption why this seciton are relevant to particular section"
    )
 
class Reference(BaseModel):
    id: int = Field(
        description="Unique identifier for the list of reference"
    )
    title: str = Field(
        description="Title of the research"
    )
    url: str = Field(
        description="Reference used in context"
    )

class Draft(BaseModel):
    id: int = Field(
        description="Unique identifier for the list of task"
    )
    section: str = Field(
        description="Name of the section in the report"
    )
    content: str = Field(
        description="Content oof the section generated by LLM"
    )
    reference: List[Reference] = Field(
        description="List of source used to generate content"
    )
    
class FollowQuestion(BaseModel):
    question: List[SearchQuery] = Field(
        description="List of follow up question generated by LLM"
    )
    
    