from typing import TypedDict, List, Annotated, Literal
import operator

from langgraph.graph import add_messages


class Summary(TypedDict): # List of answer generated by llm - Notes
    id:int
    question: str
    Summary: str

class OverallState(TypedDict):
    messages: Annotated[List, add_messages] # list of message thoughout the conversation
    query: List[dict] # List of queries asked or generated by LLMs
    search_response: Annotated[List, operator.add] # List of response geenerate by LLM 
    sources: Annotated[List, operator.add] # List of sources generated by LLM
    task_list: List[dict] # List of task 
    brief: str # breif detail of the task after asking quuestion to the user
    current_task: str | None
    current_task_id: int | None
    summary: Annotated[List[Summary], operator.add]
    max_question: int
    max_research_loop: int
    model: str
    phase: str
    
class Tasks(TypedDict):
    id: int
    task: str
    status: Literal["Completed", "In Progress", "Not Started"]
    rationale: str
    
class TaskListState(TypedDict):
    task_list: List[Tasks]

class Sources(TypedDict): # Follow question which source
    id: int
    question: str
    url: str
    summary: str
    
class Query(TypedDict):
    id: int
    query: str
    rationale: str
    
class QueryGenerationState(TypedDict):
    query: List[Query]
    